# Site settings
title: UW ChemE 375 Chemical Engineering Computer Skills
email: ccurtis7 -- AT -- uw.edu
description: "Use Excel, MatLab, and AspenPlus to solve typical chemical engineering problems. Solve realistic problems and explore alternatives that would be inaccessible for hand calculations. Includes equations of state, chemical equilibrium of simultaneous reactions, phase equilibria, plug flow reactors, heat transfer in 1D, and time-dependent heat transfer."
url: "http://uw-cheme375.github.io"
twitter_username: derchadmeister
github_username:  uw-cheme375


# Build settings
markdown: kramdown
